name: Build and Publish Docker Images

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        version: [13, 15, 16, 17, latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.${{ matrix.version }}
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/postgres:${{ matrix.version }}
            ghcr.io/${{ github.repository_owner }}/postgres:${{ matrix.version == 'latest' && 'latest' || matrix.version }}
          labels: |
            org.opencontainers.image.source=${{ github.repositoryUrl }}

      - name: Make image public
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/postgres:${{ matrix.version }}
          echo "Making $IMAGE_ID public"
          curl -X PATCH -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/user/packages/container/postgres/versions \
            -d '{"visibility":"public"}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
